# src/config/categories.py

OHE_CATEGORIES = {
    'grade': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],

    'initial_list_status': ['f', 'w'],

    'application_type': ['Individual', 'Joint App'],

    'purpose': ['car',
                'credit_card',
                'debt_consolidation',
                'educational',
                'home_improvement',
                'house',
                'major_purchase',
                'medical',
                'moving',
                'other',
                'renewable_energy',
                'small_business',
                'vacation',
                'wedding'],

    'home_ownership': ['ANY', 'MORTGAGE', 'NONE', 'OWN', 'RENT'],

    'verification_status': ['Not Verified', 'Source Verified', 'Verified'],
    
    'addr_state': ['AK',
                    'AL',
                    'AR',
                    'AZ',
                    'CA',
                    'CO',
                    'CT',
                    'DC',
                    'DE',
                    'FL',
                    'GA',
                    'HI',
                    'ID',
                    'IL',
                    'IN',
                    'KS',
                    'KY',
                    'LA',
                    'MA',
                    'MD',
                    'ME',
                    'MI',
                    'MN',
                    'MO',
                    'MS',
                    'MT',
                    'NC',
                    'ND',
                    'NE',
                    'NH',
                    'NJ',
                    'NM',
                    'NV',
                    'NY',
                    'OH',
                    'OK',
                    'OR',
                    'PA',
                    'RI',
                    'SC',
                    'SD',
                    'TN',
                    'TX',
                    'UT',
                    'VA',
                    'VT',
                    'WA',
                    'WI',
                    'WV',
                    'WY']
  }